version: '3.2'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    volumes:
      - .:/build
    working_dir: /build
